SELECT *
FROM IPLPLAYERS

-- Q1) Find the total spending on players for each team:

SELECT Team, SUM(price_in_cr) as 'Total Spending'
FROM IPLPLAYERS
GROUP BY Team
ORDER BY 'Total Spending' DESC

-- Q2) Find the top 3 highest-paid "All-Rounders' accross all teams:

SELECT TOP 3 Player, Team, Price_in_cr
FROM IPLPLAYERS
WHERE Role = 'All-rounder'
ORDER BY Price_in_cr DESC


--Q3) Find the highes-priced player in each team:

--Table 1
SELECT Player, Team, Price_in_cr
FROM IPLPLAYERS
ORDER BY Price_in_cr DESC

-- whenever we need a single row for each group, we use GROUP BY
-- use join to join 2 tables

WITH CTE_MP AS(
--Table 2
SELECT Team, Max(Price_in_cr) as MaxPrice
FROM IPLPLAYERS
GROUP BY Team
)

SELECT i.Player, i.Team, c.MaxPrice
FROM IPLPLAYERS as i
JOIN CTE_MP as c on i.Team = c.Team
WHERE i.Price_in_cr = c.MaxPrice


-- Q4) RANK PLAYERS BY THEIR PRICE WITHIN EACH TEAM AND LIST THE TOP 2 FOR EVERY TEAM

-- Steps:
-- 1)we have to crerate partition and we just have to assign the rabnk for each partition
-- 2)partition = team , rank = prince_in_cr

-- Step 1: Create Partition - use Window Function


WITH RankedPlayers AS (
SELECT PLAYER, TEAM , PRICE_IN_CR,
ROW_NUMBER() OVER (PARTITION BY TEAM ORDER BY PRICE_IN_CR DESC) AS RANKWITHINTEAM
FROM IPLPLAYERS
)

SELECT Player, Team, Price_in_cr,RANKWITHINTEAM
FROM RankedPlayers
WHERE RANKWITHINTEAM <= 2


-- Q5) FIND THE MOST EXPENSIVE PLAYER FROM EACH TEAM, ALONG WITH THE SECOND-MOST EXPENSIVE PLAYER'S NAME AND PRICE 
-- (We want the first and second player for each team in the same row)

WITH RankedPlayers AS (
	SELECT PLAYER, TEAM , PRICE_IN_CR,
	ROW_NUMBER() OVER (PARTITION BY TEAM ORDER BY PRICE_IN_CR DESC) AS RANKWITHINTEAM
	FROM IPLPLAYERS
)

SELECT TEAM, 
	MAX(CASE WHEN RANKWITHINTEAM = 1 THEN Player END ) AS MostExpensivePlayer,     -- FIrst, Column use MAX beacuse we want to only show single value here, if w/o MAX, it will show a lot of values
	MAX(CASE WHEN RANKWITHINTEAM = 1 THEN PRICE_IN_CR END ) AS HighestPrice,
	MAX(CASE WHEN RANKWITHINTEAM = 2 THEN Player END ) AS SecondMostExpensivePlayer,
	MAX(CASE WHEN RANKWITHINTEAM = 2 THEN PRICE_IN_CR END ) AS SecondHighestPrice
FROM RankedPlayers
GROUP BY TEAM


-- Q6) CALCULATE THE PERCENTAGE CONTRIBUTION OF EACH PLAYER'S PRICE TO THEIR TEAM'S TOTAL SPENDING


SELECT PLAYER, TEAM , PRICE_IN_CR,
	CAST (PRICE_IN_CR/ (SUM(PRICE_IN_CR) OVER (PARTITION BY TEAM)) * 100 AS DECIMAL (10,2))AS CONTRIBUTIONPERCENTAGE
FROM IPLPLAYERS


-- Q7) CLASSIFY PLAYERS AS 'HIGH', 'MEDIUM', OR 'LOW' PRICED BASED ON THE FOLLOWING RULES:
-- HIGH: PRICE > 15 CRORE
-- MEDIUM : PRICE BETWEEN 5 AND 15
-- LOW : PRICE < 5
-- AND FIND OUT THE NUMBER OF PLAYERS IN EACH BRACKET

WITH CTE_BR AS (
SELECT TEAM , PLAYER, PRICE_IN_CR,
	CASE
		WHEN PRICE_IN_CR > 15 THEN 'High'
		WHEN PRICE_IN_CR BETWEEN 5 AND 15 THEN 'Medium'
		ELSE 'Low'
	END AS PriceCategory
FROM IPLPLAYERS
)

-- AND FIND OUT THE NUMBER OF PLAYERS IN EACH BRACKET

SELECT TEAM, PRICECATEGORY, COUNT(*) AS 'NoOfPlayers'
FROM CTE_BR
GROUP BY TEAM, PRICECATEGORY
ORDER BY TEAM, PRICECATEGORY -- SUPAYA SUSUN PARTITION BY TEAM NUMBER FIRST - TRY EXECUTE W/O THIS LINE, SEE WHAT HAPPEN


-- Q8) FIND THE AVERAGE PRICE OF INDIAN PLAYERS AND COMPARE IT WITH OVERSEAS PLAYERS USING A SUBQUERY:

	
SELECT 
	'INDIAN' AS PlayerType,
		CAST ((SELECT AVG(PRICE_IN_CR)
		FROM IPLPLAYERS
		WHERE Type LIKE 'Indian%') AS DECIMAL (10,2)) AS AvgPrice

UNION ALL -- TO COMBINE TWO TABLE

SELECT 
	'Overseas' AS PlayerType,
		CAST ((SELECT AVG(PRICE_IN_CR)
		FROM IPLPLAYERS
		WHERE Type LIKE 'Overseas%') AS DECIMAL (10,2)) AS AvgPrice


-- Q9) IDENTIFY PLAYERS WHO EARN MORE THAN THE AVERAGE PRICE OF THEIR TEAM:


SELECT *
FROM IPLPLAYERS

-----------------------

SELECT Player, Team ,Price_in_cr
FROM IPLPLAYERS P
WHERE Price_in_cr > (

	SELECT AVG(PRICE_IN_CR)                    -- THIS 3 LINES IS THE SUBQUERY	
	FROM IPLPLAYERS
	WHERE TEAM = P.TEAM
	
	)

	
SELECT Team, 
	CAST(AVG(PRICE_IN_CR) AS DECIMAL (10,2)) AS AveragePrice
FROM IPLPLAYERS    
GROUP BY tEAM
	


---- Q10) FOR EACH ROLE, FIND THE MOST EXPENSIVE PLAYER AND THEIRs PRICE USING A CORRELATED SUBQUERY

-- CORRELATED SUBQUERY = It is a subquery that reference the column from outer query.

SELECT *
FROM IPLPLAYERS

 --- OPTION 1 : 

SELECT PLAYER, Role, Price_in_cr
FROM IPLPLAYERS P
WHERE PRICE_IN_CR = (

	SELECT MAX(PRICE_IN_CR) 
	FROM IPLPLAYERS
	WHERE ROLE = P.ROLE
	)

-- OPTION 2:(USING WINDOW FUNCTION )

SELECT PLAYER, ROLE, PRICE_IN_CR
FROM (
	SELECT PLAYER, ROLE, PRICE_IN_CR,
		RANK() OVER (PARTITION BY ROLE ORDER BY PRICE_IN_CR DESC) AS RNK
	FROM IPLPLAYERS
) T
WHERE RNK = 1

--- TO COUNT HOW MANY UNIQUE VALUE ARE IN A COLUMN

SELECT COUNT (DISTINCT ROLE)
FROM IPLPLAYERS
